### PR TITLE
Backport mpolednik's goodness (github@mpolednik)

### PR DESCRIPTION
**Pull request by ghost**
- Simplify light enumeration in main loop : 4254d0b
- Add new ambilight distance calculation algorithm :   8f64314
- Refactor HSV spectrum calculations :   3df480e
- Use slight better hue correction :   bfdb106

### CODE REVIEW

**Comment by fritsch** [comment]
Thanks much. Btw. who is current upstream? I hope it is not me :-)

**Comment by ghost** [comment]
Damn that was fast, I think it's mpolednik because he did a lot (his plugin has x10 more config options)
I'm using his rep for v16 but wanted to play around v17 :)

**Comment by fritsch** [comment]
Did you test that combination on v17? I just moved to another city and did not get my light up with that code after a firmware update, but also did not invest that much time.

**Comment by ghost** [comment]
Pushed the wrong script, should be working now (just tried ambilight with 2 bulbs), will look into the simplify light enum commit, see if it was an indent pb from me or the code not applying ?
note : drink more coffee early in the morning

**Comment by fritsch** [comment]
Please rebase :-)

@mpolednik are you our new upstream? would be cool if you'd take that burden.

**Comment by mpolednik** [comment]
@fritsch No idea, but I have tons of refactoring planned!

**Comment by fritsch** [comment]
@mpolednik could you pick the v17 workarounds from my master branch? After that I would consider you upstream and advice people to use your fork. Thanks much.

**Comment by mpolednik** [comment]
Fine by me, I'll try to get to it asap. I have been mostly playing with develop branch though, how important would those fixes be there?

**Comment by fritsch** [comment]
The v17 patch and the LiveTV commit are relevant. As without them kodi v17
won't work.

Thx much
Am 14.06.2016 12:32 nachm. schrieb "Martin Polednik" <
notifications@github.com>:

**Pull request closed without merging**
